#### Задание 1

In [163]:
import numpy as np

In [164]:
#a = np.array(np.random.rand(5, 2)*100)

In [165]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [166]:
mean_a = np.mean(a,0)
mean_a

array([2. , 8.4])

#### Задание 2

In [167]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [168]:
a_centered.shape

(5, 2)

In [169]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1] / len(a_centered[:,0])
a_centered_sp 

1.6

### работа в Pandas

In [170]:
import pandas as pd

In [171]:
a= np.array([1, 2, 3])
b = np.array(['Тургенев', 'Чехов', 'Островский'])

In [172]:
c = np.array([a,b])

In [173]:
c = c.T

In [174]:
authors = pd.DataFrame(c)

In [175]:
authors.columns = ['author_id','author_name']

In [176]:
authors

author_id author_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [177]:
a = np.array([[1, 1, 1, 2, 2, 3, 3],['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],[450, 300, 350, 500, 450, 370, 290]])
a = a.T
book = pd.DataFrame(a)
book.columns = ['author_id', 'book_title', 'price']
book

author_id            book_title price
0         1           Отцы и дети   450
1         1                 Рудин   300
2         1     Дворянское гнездо   350
3         2      Толстый и тонкий   500
4         2       Дама с собачкой   450
5         3                 Гроза   370
6         3  Таланты и поклонники   290

In [179]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title price
0         1    Тургенев           Отцы и дети   450
1         1    Тургенев                 Рудин   300
2         1    Тургенев     Дворянское гнездо   350
3         2       Чехов      Толстый и тонкий   500
4         2       Чехов       Дама с собачкой   450
5         3  Островский                 Гроза   370
6         3  Островский  Таланты и поклонники   290

In [185]:
cover = pd.Series(['твердая','мягкая'])
cover

0    твердая
1     мягкая
dtype: object

In [192]:
authors_price['cover'] = [cover[0], cover[1], cover[1], cover[0], cover[0], cover[1], cover[1]]

In [203]:
authors_price['count'] = 1

In [204]:
#top5 = authors_price.sort_values(by='price', ascending=False).tail(5)
authors_price['price'] = authors_price['price'].astype('float')
#authors_price.dtypes
authors_price.nlargest(5, 'price')

author_id author_name         book_title  price    cover  count
3         2       Чехов   Толстый и тонкий  500.0  твердая      1
0         1    Тургенев        Отцы и дети  450.0  твердая      1
4         2       Чехов    Дама с собачкой  450.0  твердая      1
5         3  Островский              Гроза  370.0   мягкая      1
2         1    Тургенев  Дворянское гнездо  350.0   мягкая      1

In [207]:
authors_stat = authors_price.groupby('author_name').agg({'price': 'min'})
authors_stat = pd.concat([authors_stat, authors_price.groupby('author_name').agg({'price': 'max'})], axis=1, ignore_index=True)
authors_stat = pd.concat([authors_stat, authors_price.groupby('author_name').agg({'price': 'mean'})], axis=1, ignore_index=True)
#authors_stat = authors_stat.rename(columns={'0':'min_price', '1':'max_price', '2':'mean_price'})
authors_stat.columns = ['min_price', 'max_price', 'mean_price']
authors_stat.reset_index()

author_name  min_price  max_price  mean_price
0  Островский      290.0      370.0  330.000000
1    Тургенев      300.0      450.0  366.666667
2       Чехов      450.0      500.0  475.000000

In [214]:
?pd.pivot_table

In [223]:
book_info = authors_price.pivot_table(index=['author_name'], columns=['cover'], values='price', aggfunc='sum')
book_info = book_info.fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [224]:
book_info.to_excel("test.xlsx")

In [228]:
book2 = pd.read_excel("test.xlsx")

In [229]:
book2

author_name  мягкая  твердая
0  Островский     660        0
1    Тургенев     650      450
2       Чехов       0      950